In [4]:
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np
import copy
from sklearn.linear_model import LinearRegression

In [5]:
df = pd.read_csv("train.csv", nrows=100000)
df.head()

,Semana,Agencia_ID,Canal_ID,Ruta_SAK,Cliente_ID,Producto_ID,Venta_uni_hoy,Venta_hoy,Dev_uni_proxima,Dev_proxima,Demanda_uni_equil
0,3,1110,7,3301,15766,1212,3,25.14,0,0.0,3
1,3,1110,7,3301,15766,1216,4,33.52,0,0.0,4
2,3,1110,7,3301,15766,1238,4,39.32,0,0.0,4
3,3,1110,7,3301,15766,1240,4,33.52,0,0.0,4
4,3,1110,7,3301,15766,1242,3,22.92,0,0.0,3

In [8]:
print('cantidad de observaciones (clientes): ',df.shape[0])
print('cantidad de variables: ',df.shape[1])
print(df.shape)

cantidad de observaciones (clientes):  100000
cantidad de variables:  11
(100000, 11)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Semana             100000 non-null  int64
 1   Agencia_ID         100000 non-null  int64
 2   Canal_ID           100000 non-null  int64
 3   Ruta_SAK           100000 non-null  int64
 4   Cliente_ID         100000 non-null  int64
 5   Producto_ID        100000 non-null  int64
 6   Venta_uni_hoy      100000 non-null  int64
 7   Venta_hoy          100000 non-null  float64
 8   Dev_uni_proxima    100000 non-null  int64
 9   Dev_proxima        100000 non-null  float64
 10  Demanda_uni_equil  100000 non-null  int64
dtypes: float64(2), int64(9)
memory usage: 8.4 MB

In [10]:
df.describe()

,Semana,Agencia_ID,Canal_ID,Ruta_SAK,Cliente_ID,Producto_ID,Venta_uni_hoy,Venta_hoy,Dev_uni_proxima,Dev_proxima,Demanda_uni_equil
count,100000.0,100000.000000,100000.000000,100000.00000,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,3.0,1111.166260,1.511530,1780.27560,1.173254e+06,14733.063630,6.649590,64.373366,0.091370,0.902621,6.604250
std,0.0,0.546718,1.761198,997.85845,1.488697e+06,17522.419476,18.487354,160.315317,3.995986,17.838545,18.486129
min,3.0,1110.000000,1.000000,1001.00000,1.407500e+04,72.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.0,1111.000000,1.000000,1101.00000,6.527800e+04,1220.000000,2.000000,20.280000,0.000000,0.000000,2.000000
50%,3.0,1111.000000,1.000000,1412.00000,4.188630e+05,2233.000000,4.000000,37.500000,0.000000,0.000000,4.000000
75%,3.0,1111.000000,1.000000,1642.00000,1.785102e+06,32819.000000,7.000000,69.700000,0.000000,0.000000,7.000000
max,3.0,1112.000000,11.000000,4501.00000,9.747286e+06,49994.000000,2000.000000,15561.000000,1008.000000,3030.880000,2000.000000

In [11]:
df.head()

,Semana,Agencia_ID,Canal_ID,Ruta_SAK,Cliente_ID,Producto_ID,Venta_uni_hoy,Venta_hoy,Dev_uni_proxima,Dev_proxima,Demanda_uni_equil
0,3,1110,7,3301,15766,1212,3,25.14,0,0.0,3
1,3,1110,7,3301,15766,1216,4,33.52,0,0.0,4
2,3,1110,7,3301,15766,1238,4,39.32,0,0.0,4
3,3,1110,7,3301,15766,1240,4,33.52,0,0.0,4
4,3,1110,7,3301,15766,1242,3,22.92,0,0.0,3

In [30]:
for colu in df.columns:
    cantidad = df[colu].value_counts()
    #print(f"Nombre de Columna {colu}: Tiene {cantidad} valores.\n----")
    print(f"{cantidad} \n-------" )

Semana
3    100000
Name: count, dtype: int64
-------
Agencia_ID
1111    67346
1112    24640
1110     8014
Name: count, dtype: int64
-------
Canal_ID
1     91986
7      6931
11      662
8       421
Name: count, dtype: int64
-------
Ruta_SAK
1410    1916
1415    1849
1407    1785
1404    1635
1411    1535
        ...
3404      93
3401      92
3405      81
3406      44
3407      13
Name: count, Length: 151, dtype: int64
-------
Cliente_ID
56717      96
68056      90
22248      90
1578019    89
39024      88
           ..
49123       1
1598964     1
4646259     1
2306392     1
4395193     1
Name: count, Length: 5835, dtype: int64
-------
Producto_ID
2233     3075
1250     3009
1240     2764
1278     2761
35651    2703
         ...
36791       1
30235       1
30236       1
31779       1
31198       1
Name: count, Length: 287, dtype: int64
-------
Venta_uni_hoy
2      18445
1      13629
3      12950
4       9982
5       9845
       ...
92         1
273        1
462        1
260        1
107        1
Name: count, Length: 178, dtype: int64
-------
Venta_hoy
16.76      1368
15.28      1095
16.30      1087
8.38       1026
16.67      1025
           ...
720.00        1
3485.00       1
5368.00       1
1975.00       1
192.42        1
Name: count, Length: 2333, dtype: int64
-------
Dev_uni_proxima
0       97559
1        1179
2         563
3         220
4         126
5         109
6          54
7          31
8          24
10         17
9          16
11         14
12         13
15         10
20          7
14          7
24          5
21          4
13          4
19          4
30          3
40          3
18          3
25          3
28          2
35          2
17          2
16          2
672         1
152         1
60          1
1008        1
110         1
76          1
48          1
43          1
55          1
50          1
38          1
26          1
150         1
27          1
Name: count, dtype: int64
-------
Dev_proxima
0.00      97559
8.38        205
16.76        93
7.59         64
21.32        55
          ...
233.38        1
137.62        1
167.60        1
91.68         1
63.00         1
Name: count, Length: 444, dtype: int64
-------
Demanda_uni_equil
2      18190
1      13484
3      12833
4       9892
5       9758
       ...
92         1
273        1
462        1
260        1
107        1
Name: count, Length: 178, dtype: int64
-------